server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**

        - id: seckill-service
          uri: lb://seckill-service
          predicates:
            - Path=/seckill/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true



